### ISSUE TITLE
大佬，经过两年的研究，输入密钥后不生成连接

### ISSUE THREAD

**Issue by mlmk6698** [ckfanzhe/Locate#32]
![mmexport1706872640679.png](https://github.com/ckfanzhe/Locate/assets/85853590/06497a7a-98e6-40d6-b79b-ad283580c3f1)

**Comment by ckfanzhe** [comment]
可能api已经更新了吧，或者提供服务的页面已经跑路了，可以手动尝试访问api的页面看看？是不是有新接口了；这个爬虫主要还是调用的第三方api进行的定位操作
